"""
Auto-generated Python ontology module — DO NOT EDIT BY HAND.

Generated from:
  pulsar-web/src/data/ontology/vla.json (v2.0.0)
  pulsar-web/src/data/ontology/ai.json  (v2.0.0)

Regenerate with:
  cd pulsar-web && pnpm build-ontology-py
  (also runs as part of pnpm build)

Public API:
  ONTOLOGY: dict[slug, dict]               — every node by slug
  LEAVES: list[str]                        — slugs with match_precedence > 0
  CATCH_ALL: set[str]                      — match_precedence in (0, 10]
  KEYWORDS: dict[slug, list[str]]          — leaves only
  ALIAS_V1_TO_V2: dict[str, str | None]    — V1 → V2 alias map (None = retired)
  rank_method_families(titles: list[str]) -> list[tuple[str, int]]
      Per-title pick: highest match_precedence wins ties; among equals,
      highest keyword-hit count wins. Mirrors TS rankMethodFamiliesV2.

Generated at: 2026-05-24T04:00:01.865Z
"""

ONTOLOGY = {
    "vla": {
        "parents": [],
        "primary_parent": None,
        "domain": "vla",
        "display_name": "VLA",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.foundation": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Foundation Models",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.foundation.vla_generalist": {
        "parents": ["vla.foundation"],
        "primary_parent": "vla.foundation",
        "domain": "vla",
        "display_name": "VLA Generalist",
        "keywords": ["vla policy","vla model","vision-language-action policy","rt-2","openvla","π0","gr00t","helix policy","generalist vla"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.foundation.cross_embodiment_fm": {
        "parents": ["vla.foundation"],
        "primary_parent": "vla.foundation",
        "domain": "vla",
        "display_name": "Cross-Embodiment Foundation Models",
        "keywords": ["cross-embodiment","cross embodiment","open-x","open x-embodiment","rt-x","octo policy","crossformer","rdt-1b","heterogeneous policy","hpt policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.foundation.dual_system_vla": {
        "parents": ["vla.foundation"],
        "primary_parent": "vla.foundation",
        "domain": "vla",
        "display_name": "Dual-System VLA",
        "keywords": ["dual-system vla","system 1 system 2","system-1 system-2","fast slow policy","helix s1 s2","hi robot","lcb policy","slow-fast vla"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.foundation.vlm_grounded_policy": {
        "parents": ["vla.foundation"],
        "primary_parent": "vla.foundation",
        "domain": "vla",
        "display_name": "VLM-Grounded Policy",
        "keywords": ["voxposer","moka policy","pivot policy","rekep","code as policies","code-as-policies","vlm grounding policy","value map policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.action": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Action Representation",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.action.action_tokenization": {
        "parents": ["vla.action"],
        "primary_parent": "vla.action",
        "domain": "vla",
        "display_name": "Action Tokenization",
        "keywords": ["action tokenization","action tokens","fast tokens","bpe action","action codebook","discretized action","bin tokens","quest tokenizer"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.action.flow_matching": {
        "parents": ["vla.action"],
        "primary_parent": "vla.action",
        "domain": "vla",
        "display_name": "Flow Matching",
        "keywords": ["flow matching","flow-matching","rectified flow","rectflow","mean flow","mean-flow","consistency flow","flow policy","flow vla","discrete flow"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.action.diffusion_policy": {
        "parents": ["vla.action"],
        "primary_parent": "vla.action",
        "domain": "vla",
        "display_name": "Diffusion Policy",
        "keywords": ["diffusion policy","diffusion policies","ddpm action","score-based policy","diffusion head","denoising policy","dp3","diffusion-based action","diffusion vla"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.action.autoregressive_action": {
        "parents": ["vla.action"],
        "primary_parent": "vla.action",
        "domain": "vla",
        "display_name": "Autoregressive Action",
        "keywords": ["autoregressive action","ar action policy","openvla ar","rt-2 ar","next-action token","autoregressive vla"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.action.continuous_regression_head": {
        "parents": ["vla.action"],
        "primary_parent": "vla.action",
        "domain": "vla",
        "display_name": "Continuous Regression Head",
        "keywords": ["mse action head","regression policy head","mlp action head","continuous regression head","deterministic action head"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.policy": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Policy Learning",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.policy.imitation_learning": {
        "parents": ["vla.policy"],
        "primary_parent": "vla.policy",
        "domain": "vla",
        "display_name": "Imitation Learning",
        "keywords": ["imitation learning","behavior cloning","behavioral cloning","act policy","diffusion policy training","umi data","demonstration policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.policy.residual_policy": {
        "parents": ["vla.policy"],
        "primary_parent": "vla.policy",
        "domain": "vla",
        "display_name": "Residual Policy",
        "keywords": ["residual policy","residual rl","residual correction","resip","rfm residual","residual learning policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.policy.inverse_dynamics_models": {
        "parents": ["vla.policy"],
        "primary_parent": "vla.policy",
        "domain": "vla",
        "display_name": "Inverse Dynamics Models",
        "keywords": ["inverse dynamics","latent action","lapa policy","genima labels","vid2robot","action labeling video"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.policy.robot_rl": {
        "parents": ["vla.policy"],
        "primary_parent": "vla.policy",
        "domain": "vla",
        "display_name": "Robot RL",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.policy.robot_rl.online_robot_rl": {
        "parents": ["vla.policy.robot_rl"],
        "primary_parent": "vla.policy.robot_rl",
        "domain": "vla",
        "display_name": "Online Robot RL",
        "keywords": ["online robot rl","on-robot rl","hil-serl","serl framework","human-in-the-loop rl"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.policy.robot_rl.offline_robot_rl": {
        "parents": ["vla.policy.robot_rl"],
        "primary_parent": "vla.policy.robot_rl",
        "domain": "vla",
        "display_name": "Offline Robot RL",
        "keywords": ["offline robot rl","cal-ql","iql demos","q-transformer","conservative q-learning robot"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.policy.robot_rl.vla_post_training_rl": {
        "parents": ["vla.policy.robot_rl"],
        "primary_parent": "vla.policy.robot_rl",
        "domain": "vla",
        "display_name": "VLA Post-Training RL",
        "keywords": ["ire-vla","pa-rl","grpo-for-vla","rl fine-tune vla","vla post-training rl","rl fine-tuning vla"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.manipulation": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Manipulation Skills",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.manipulation.dexterous_manipulation": {
        "parents": ["vla.manipulation"],
        "primary_parent": "vla.manipulation",
        "domain": "vla",
        "display_name": "Dexterous Manipulation",
        "keywords": ["dexterous manipulation","dexterous grasp","dexgrasp","in-hand manipulation","multi-finger","fingertip control","anydexgrasp"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.manipulation.bimanual_manipulation": {
        "parents": ["vla.manipulation"],
        "primary_parent": "vla.manipulation",
        "domain": "vla",
        "display_name": "Bimanual Manipulation",
        "keywords": ["bimanual manipulation","two-arm policy","aloha policy","mobile aloha","bidex policy","dual-arm coordination"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.manipulation.mobile_manipulation": {
        "parents": ["vla.manipulation"],
        "primary_parent": "vla.manipulation",
        "domain": "vla",
        "display_name": "Mobile Manipulation",
        "keywords": ["mobile manipulation","mobile aloha","tidybot","ok-robot","wheeled manipulator","base-arm coordination"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.manipulation.contact_rich_assembly": {
        "parents": ["vla.manipulation"],
        "primary_parent": "vla.manipulation",
        "domain": "vla",
        "display_name": "Contact-Rich Assembly",
        "keywords": ["contact-rich assembly","contact rich manipulation","industreal","automate assembly","peg-in-hole policy","force-controlled assembly"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.manipulation.tactile_sensing": {
        "parents": ["vla.manipulation"],
        "primary_parent": "vla.manipulation",
        "domain": "vla",
        "display_name": "Tactile Sensing",
        "keywords": ["tactile sensing","tactile representation","visuo-tactile","visuotactile","haptic sensing","anyskin","digit-360","t-dex"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.locomotion": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Locomotion & Whole-Body",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.locomotion.humanoid_whole_body": {
        "parents": ["vla.locomotion"],
        "primary_parent": "vla.locomotion",
        "domain": "vla",
        "display_name": "Humanoid Whole-Body",
        "keywords": ["humanoid whole-body","whole-body control","wbc policy","omnih2o","humanplus","helix wbc","gr00t wbc","h2o policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.locomotion.legged_locomotion": {
        "parents": ["vla.locomotion"],
        "primary_parent": "vla.locomotion",
        "domain": "vla",
        "display_name": "Legged Locomotion",
        "keywords": ["legged locomotion","quadruped locomotion","extreme parkour","anymal parkour","dtc locomotion","rough terrain locomotion"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.locomotion.loco_manipulation": {
        "parents": ["vla.locomotion"],
        "primary_parent": "vla.locomotion",
        "domain": "vla",
        "display_name": "Loco-Manipulation",
        "keywords": ["loco-manipulation","loco manipulation","umi-on-legs","humanplus arm","legged manipulation"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.perception": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Perception for Action",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.perception.representation_3d": {
        "parents": ["vla.perception"],
        "primary_parent": "vla.perception",
        "domain": "vla",
        "display_name": "3D Representation",
        "keywords": ["3d representation","3d policy","3d scene encoder","voxel policy","point cloud policy","rvt-2","idp3 policy","nerf for robot"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.perception.gaussian_splat_robotics": {
        "parents": ["vla.perception"],
        "primary_parent": "vla.perception",
        "domain": "vla",
        "display_name": "Gaussian Splat Robotics",
        "keywords": ["gaussian splatting","3d gaussian splat","3dgs policy","splat-mover","robosplat","gaussian splat scene"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.perception.affordance_grounding": {
        "parents": ["vla.perception"],
        "primary_parent": "vla.perception",
        "domain": "vla",
        "display_name": "Affordance Grounding",
        "keywords": ["affordance grounding","affordance keypoint","voxposer","moka affordance","rekep affordance","robopoint","value-map grounding"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.perception.visual_pretraining_for_robots": {
        "parents": ["vla.perception"],
        "primary_parent": "vla.perception",
        "domain": "vla",
        "display_name": "Visual Pretraining for Robots",
        "keywords": ["visual pretraining robot","r3m encoder","vc-1 encoder","theia encoder","visual representation for robot"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.reasoning": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Reasoning for Embodiment",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.reasoning.embodied_cot": {
        "parents": ["vla.reasoning"],
        "primary_parent": "vla.reasoning",
        "domain": "vla",
        "display_name": "Embodied CoT",
        "keywords": ["embodied cot","embodied chain-of-thought","ecot","cot-vla","rt-h","chain-of-thought policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.reasoning.hierarchical_planning": {
        "parents": ["vla.reasoning"],
        "primary_parent": "vla.reasoning",
        "domain": "vla",
        "display_name": "Hierarchical Planning",
        "keywords": ["hierarchical planning","task and motion planning","saycan","hi robot planner","lcb planner","high-level planner"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.reasoning.error_recovery_replanning": {
        "parents": ["vla.reasoning"],
        "primary_parent": "vla.reasoning",
        "domain": "vla",
        "display_name": "Error Recovery & Replanning",
        "keywords": ["error recovery","replanning policy","reflect framework","doremi recovery","olaf recovery","failure detection policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.world": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Generative World Models",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.world.world_model_dynamics": {
        "parents": ["vla.world"],
        "primary_parent": "vla.world",
        "domain": "vla",
        "display_name": "World Model Dynamics",
        "keywords": ["world model dynamics","latent dynamics model","dreamerv3","daydreamer","gr-1 robot","gr-2 robot","ivideogpt"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.world.video_generation_for_robotics": {
        "parents": ["vla.world"],
        "primary_parent": "vla.world",
        "domain": "vla",
        "display_name": "Video Generation for Robotics",
        "keywords": ["video generation robotics","video planner","unipi policy","robodreamer","gr00t dreams","cosmos world","video prediction for robot"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.world.neural_simulator": {
        "parents": ["vla.world"],
        "primary_parent": "vla.world",
        "domain": "vla",
        "display_name": "Neural Simulator",
        "keywords": ["neural simulator","1x world model","genie 2 sim","learned simulator","playable world model"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.sim_data": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Sim-to-Real & Data",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.sim_data.sim_to_real": {
        "parents": ["vla.sim_data"],
        "primary_parent": "vla.sim_data",
        "domain": "vla",
        "display_name": "Sim-to-Real",
        "keywords": ["sim-to-real","sim to real","sim2real","domain randomization","rialto sim2real","dr-ft policy"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.sim_data.real_to_sim": {
        "parents": ["vla.sim_data"],
        "primary_parent": "vla.sim_data",
        "domain": "vla",
        "display_name": "Real-to-Sim",
        "keywords": ["real-to-sim","real to sim","urdformer","robocasa scene","digital cousins","scene reconstruction sim"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.sim_data.data_collection_systems": {
        "parents": ["vla.sim_data"],
        "primary_parent": "vla.sim_data",
        "domain": "vla",
        "display_name": "Data Collection Systems",
        "keywords": ["data collection system","umi gripper","dexcap","hato teleop","anyteleop","teleoperation rig"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.sim_data.synthetic_data_generation": {
        "parents": ["vla.sim_data"],
        "primary_parent": "vla.sim_data",
        "domain": "vla",
        "display_name": "Synthetic Data Generation",
        "keywords": ["synthetic data generation robot","robogen","dexmimicgen","gr00t-mimic","procedural trajectory generation"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.sim_data.vla_scaling_laws": {
        "parents": ["vla.sim_data"],
        "primary_parent": "vla.sim_data",
        "domain": "vla",
        "display_name": "VLA Scaling Laws",
        "keywords": ["vla scaling laws","robot scaling laws","octo scaling","rdt-1b scaling","dataset scaling vla","tuyls scaling"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.efficiency": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Efficient Inference",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.efficiency.vla_acceleration": {
        "parents": ["vla.efficiency"],
        "primary_parent": "vla.efficiency",
        "domain": "vla",
        "display_name": "VLA Acceleration",
        "keywords": ["tinyvla","deer-vla","openvla-oft","vla acceleration","vla quantization","vla distillation","vla pruning","fast vla inference"],
        "match_precedence": 10,
        "effective_date": "2026-05-24",
    },
    "vla.efficiency.async_inference": {
        "parents": ["vla.efficiency"],
        "primary_parent": "vla.efficiency",
        "domain": "vla",
        "display_name": "Async Inference",
        "keywords": ["async inference","asynchronous inference","action chunking","rtc policy","real-time chunking"],
        "match_precedence": 10,
        "effective_date": "2026-05-24",
    },
    "vla.navigation": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Navigation",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.navigation.vision_language_navigation": {
        "parents": ["vla.navigation"],
        "primary_parent": "vla.navigation",
        "domain": "vla",
        "display_name": "Vision-Language Navigation",
        "keywords": ["vision-language navigation","visual navigation policy","navid","nomad policy","vint navigation","vln benchmark"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.navigation.autonomous_driving_e2e": {
        "parents": ["vla.navigation"],
        "primary_parent": "vla.navigation",
        "domain": "vla",
        "display_name": "Autonomous Driving (E2E)",
        "keywords": ["autonomous driving end-to-end","e2e driving","uniad","drivevlm","emma driving","end-to-end self-driving"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.eval": {
        "parents": ["vla"],
        "primary_parent": "vla",
        "domain": "vla",
        "display_name": "Safety, Eval & Benchmarks",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "vla.eval.robot_safety": {
        "parents": ["vla.eval"],
        "primary_parent": "vla.eval",
        "domain": "vla",
        "display_name": "Robot Safety",
        "keywords": ["robot safety","safe rl manipulation","iso-compliant policy","safe contact","safety-aware policy","safety filter robot"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.eval.robot_eval_benchmarks": {
        "parents": ["vla.eval"],
        "primary_parent": "vla.eval",
        "domain": "vla",
        "display_name": "Robot Eval Benchmarks",
        "keywords": ["libero benchmark","simplerenv","roboarena","calvin benchmark","robocasa benchmark","robot benchmark suite"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "vla.eval.failure_analysis_robotics": {
        "parents": ["vla.eval"],
        "primary_parent": "vla.eval",
        "domain": "vla",
        "display_name": "Robotics Failure Analysis",
        "keywords": ["robofac","reflect-eval","robot failure analysis","robotics failure taxonomy","manipulation failure modes"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai": {
        "parents": [],
        "primary_parent": None,
        "domain": "ai",
        "display_name": "AI Agent",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.tools": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Tool Use & Action Surfaces",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.tools.mcp_protocol": {
        "parents": ["ai.tools"],
        "primary_parent": "ai.tools",
        "domain": "ai",
        "display_name": "MCP (Model Context Protocol)",
        "keywords": ["mcp","model context protocol","context protocol","fastmcp","mcp server","mcp-python-sdk"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.tools.function_calling": {
        "parents": ["ai.tools"],
        "primary_parent": "ai.tools",
        "domain": "ai",
        "display_name": "Function Calling",
        "keywords": ["function calling","function-calling","tool use api","tool_use","openai tools api","gemini function-calling","structured tool call"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.tools.code_execution_tools": {
        "parents": ["ai.tools"],
        "primary_parent": "ai.tools",
        "domain": "ai",
        "display_name": "Code-Execution Tools",
        "keywords": ["code execution tool","code interpreter","codeact","e2b sandbox","modal sandbox","claude code bash","code sandbox tool"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.tools.browser_use": {
        "parents": ["ai.tools"],
        "primary_parent": "ai.tools",
        "domain": "ai",
        "display_name": "Browser Use",
        "keywords": ["browser use","browseruse","playwright-mcp","stagehand browser","browser automation agent","headless browser agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.computer_use": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Computer Use & GUI Agents",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.computer_use.computer_use_desktop": {
        "parents": ["ai.computer_use"],
        "primary_parent": "ai.computer_use",
        "domain": "ai",
        "display_name": "Computer Use (Desktop)",
        "keywords": ["computer use","computer-use agent","operator agent","ui-tars","cradle agent","desktop gui agent","screenshot mouse keyboard"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.computer_use.mobile_agent": {
        "parents": ["ai.computer_use"],
        "primary_parent": "ai.computer_use",
        "domain": "ai",
        "display_name": "Mobile Agent",
        "keywords": ["mobile agent","android agent","autodroid","mobileagent-v3","app intents","phone gui agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.context": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Memory & Context",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.context.context_engineering": {
        "parents": ["ai.context"],
        "primary_parent": "ai.context",
        "domain": "ai",
        "display_name": "Context Engineering",
        "keywords": ["context engineering","context-engineering","repoprompt","cline rules","prompt scaffolding","context shaping"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.context.agent_memory": {
        "parents": ["ai.context"],
        "primary_parent": "ai.context",
        "domain": "ai",
        "display_name": "Agent Memory",
        "keywords": ["agent memory","memgpt","letta memory","zep memory","mem0","langmem","persistent memory store"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.context.long_context": {
        "parents": ["ai.context"],
        "primary_parent": "ai.context",
        "domain": "ai",
        "display_name": "Long Context",
        "keywords": ["long context","long-context","1m context","million-token context","ruler benchmark","extended context window"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.reasoning": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Reasoning & Planning",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.reasoning.reasoning_planning": {
        "parents": ["ai.reasoning"],
        "primary_parent": "ai.reasoning",
        "domain": "ai",
        "display_name": "Explicit Reasoning (CoT / Search)",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.reasoning.reasoning_planning.chain_of_thought": {
        "parents": ["ai.reasoning.reasoning_planning"],
        "primary_parent": "ai.reasoning.reasoning_planning",
        "domain": "ai",
        "display_name": "Chain-of-Thought",
        "keywords": ["chain-of-thought","chain of thought","extended thinking","o1-preview","thinking trace","inline reasoning trace"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.reasoning.reasoning_planning.tree_search_planning": {
        "parents": ["ai.reasoning.reasoning_planning"],
        "primary_parent": "ai.reasoning.reasoning_planning",
        "domain": "ai",
        "display_name": "Tree-Search Planning",
        "keywords": ["tree search planning","monte carlo tree","rstar-math","alphaproof","tree-of-thoughts","lats agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.reasoning.world_model_llm": {
        "parents": ["ai.reasoning"],
        "primary_parent": "ai.reasoning",
        "domain": "ai",
        "display_name": "World Model (LLM)",
        "keywords": ["genie 3","voyager agent","world model agent","worlddreamer agent","open-ended world model llm"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.multi_agent": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Multi-Agent Orchestration",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.multi_agent.multi_agent": {
        "parents": ["ai.multi_agent"],
        "primary_parent": "ai.multi_agent",
        "domain": "ai",
        "display_name": "Multi-Agent Teams",
        "keywords": ["multi-agent","multi agent","multiagent","agent collaboration","agent orchestration","crewai","autogen","openai swarm","metagpt"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.multi_agent.agent_protocols": {
        "parents": ["ai.multi_agent"],
        "primary_parent": "ai.multi_agent",
        "domain": "ai",
        "display_name": "Agent Protocols (A2A/ACP)",
        "keywords": ["a2a protocol","agent-to-agent protocol","acp protocol","agntcy","inter-agent protocol","open agent protocol"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.multi_agent.agent_handoff": {
        "parents": ["ai.multi_agent"],
        "primary_parent": "ai.multi_agent",
        "domain": "ai",
        "display_name": "Agent Handoff",
        "keywords": ["agent handoff","supervisor agent","sub-agent handoff","langgraph supervisor","claude sub-agents","agent routing handoff"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.coding": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Coding Agents",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.coding.agentic_coding": {
        "parents": ["ai.coding"],
        "primary_parent": "ai.coding",
        "domain": "ai",
        "display_name": "Agentic Coding",
        "keywords": ["agentic coding","coding agent","claude code","cursor agent","aider coder","devin agent","software engineer agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.coding.code_review_agent": {
        "parents": ["ai.coding"],
        "primary_parent": "ai.coding",
        "domain": "ai",
        "display_name": "Code-Review Agent",
        "keywords": ["code review agent","ai code review","coderabbit","greptile review","graphite diamond","pr review bot"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.coding.repo_indexing": {
        "parents": ["ai.coding"],
        "primary_parent": "ai.coding",
        "domain": "ai",
        "display_name": "Repo Indexing",
        "keywords": ["repo indexing","code indexing","sourcegraph cody","codeium cortex","sweep coding","repository-scale retrieval"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.rag": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "RAG & Retrieval",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.rag.rag_classic": {
        "parents": ["ai.rag"],
        "primary_parent": "ai.rag",
        "domain": "ai",
        "display_name": "Classic RAG",
        "keywords": ["classic rag","llamaindex rag","langchain rag","cohere rerank","embedding rag","vector retrieval rag"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.rag.graph_rag": {
        "parents": ["ai.rag"],
        "primary_parent": "ai.rag",
        "domain": "ai",
        "display_name": "Graph RAG",
        "keywords": ["graph rag","graphrag","lightrag","neo4j llm graph","knowledge graph rag"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.rag.agentic_rag": {
        "parents": ["ai.rag"],
        "primary_parent": "ai.rag",
        "domain": "ai",
        "display_name": "Agentic RAG",
        "keywords": ["agentic rag","self-rag","adaptive-rag","perplexity pro","iterative retrieval agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.eval": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Agentic Evaluation",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.eval.agent_eval": {
        "parents": ["ai.eval"],
        "primary_parent": "ai.eval",
        "domain": "ai",
        "display_name": "Agent Eval",
        "keywords": ["swe-bench verified","gaia benchmark","osworld","tau-bench","browsecomp","agent benchmark suite"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.eval.agent_observability": {
        "parents": ["ai.eval"],
        "primary_parent": "ai.eval",
        "domain": "ai",
        "display_name": "Agent Observability",
        "keywords": ["langsmith","braintrust eval","arize phoenix","logfire observability","agent tracing platform","agent observability"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.eval.failure_taxonomy": {
        "parents": ["ai.eval"],
        "primary_parent": "ai.eval",
        "domain": "ai",
        "display_name": "Failure Taxonomy",
        "keywords": ["failure taxonomy","agent failure modes","agent post-mortem","agentbench failure","failure categorization"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.safety": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Agent Safety & Alignment",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.safety.agent_safety": {
        "parents": ["ai.safety"],
        "primary_parent": "ai.safety",
        "domain": "ai",
        "display_name": "Agent Safety",
        "keywords": ["nemo guardrails","lakera guardrails","invariant labs","agent guardrail runtime","policy enforcement agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.safety.prompt_injection_defense": {
        "parents": ["ai.safety"],
        "primary_parent": "ai.safety",
        "domain": "ai",
        "display_name": "Prompt-Injection Defense",
        "keywords": ["prompt injection defense","prompt-injection defense","camel defense","spotlight defense","indirect prompt injection"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.safety.agent_red_team": {
        "parents": ["ai.safety"],
        "primary_parent": "ai.safety",
        "domain": "ai",
        "display_name": "Agent Red-Team",
        "keywords": ["harmbench","agentdojo","cybench","agent red team","red-team agent eval","adversarial agent benchmark"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.infra": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Frameworks & Infrastructure",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.infra.agent_framework": {
        "parents": ["ai.infra"],
        "primary_parent": "ai.infra",
        "domain": "ai",
        "display_name": "Agent Framework",
        "keywords": ["langgraph","openai agents sdk","claude agent sdk","pydantic-ai","mastra framework","agent sdk","agent framework library"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.infra.agent_runtime": {
        "parents": ["ai.infra"],
        "primary_parent": "ai.infra",
        "domain": "ai",
        "display_name": "Agent Runtime",
        "keywords": ["openai assistants v2","bedrock agentcore","cloudflare agents runtime","vercel ai sdk","managed agent runtime","hosted agent runtime"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.infra.agent_infra": {
        "parents": ["ai.infra"],
        "primary_parent": "ai.infra",
        "domain": "ai",
        "display_name": "Agent Infra",
        "keywords": ["vllm serving","sglang serving","prompt-caching api","routellm","kv-cache serving","model serving infra"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.frontier": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Frontier Capabilities",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.frontier.frontier_model": {
        "parents": ["ai.frontier"],
        "primary_parent": "ai.frontier",
        "domain": "ai",
        "display_name": "Frontier Models",
        "keywords": ["gpt-5","gpt 5","claude opus","claude sonnet","gemini 3 pro","deepseek-v3","frontier model release","foundation model release"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.frontier.voice_multimodal": {
        "parents": ["ai.frontier"],
        "primary_parent": "ai.frontier",
        "domain": "ai",
        "display_name": "Voice & Multimodal",
        "keywords": ["voice agent","speech-to-speech","gpt realtime","gemini live","pipecat","ultravox","full-duplex voice","omni-modal speech"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
    "ai.vertical": {
        "parents": ["ai"],
        "primary_parent": "ai",
        "domain": "ai",
        "display_name": "Vertical / Domain",
        "keywords": [],
        "match_precedence": 0,
        "effective_date": "2026-05-24",
    },
    "ai.vertical.vertical_agent": {
        "parents": ["ai.vertical"],
        "primary_parent": "ai.vertical",
        "domain": "ai",
        "display_name": "Vertical Agents",
        "keywords": ["vertical agent","harvey legal","sierra cx","glean work agent","openevidence clinical","domain-specific agent","legal agent","clinical agent"],
        "match_precedence": 100,
        "effective_date": "2026-05-24",
    },
}

ALIAS_V1_TO_V2 = {
    "flow_matching": "vla.action.flow_matching",
    "diffusion_policy": "vla.action.diffusion_policy",
    "world_model": "vla.world.world_model_dynamics",
    "agentic_coding": "ai.coding.agentic_coding",
    "mcp_protocol": "ai.tools.mcp_protocol",
    "multi_agent": "ai.multi_agent.multi_agent",
    "context_engineering": "ai.context.context_engineering",
    "agent_safety": "ai.safety.agent_safety",
    "agent_eval": "ai.eval.agent_eval",
    "agent_infra": "ai.infra.agent_infra",
    "open_source": None,
    "voice_multimodal": "ai.frontier.voice_multimodal",
    "reasoning_planning": "ai.reasoning.reasoning_planning",
    "frontier_model": "ai.frontier.frontier_model",
    "vertical_agent": "ai.vertical.vertical_agent",
    "3d_representation": "vla.perception.representation_3d",
    "vla_core": "vla.foundation.vla_generalist",
    "cross_embodiment": "vla.foundation.cross_embodiment_fm",
    "dexterous_hand": "vla.manipulation.dexterous_manipulation",
    "human_robot": "vla.policy.imitation_learning",
    "instruction_tuning": "vla.policy.imitation_learning",
    "language_grounding": "vla.foundation.vla_generalist",
    "long_horizon": "vla.reasoning.hierarchical_planning",
    "mobile_manipulation": "vla.manipulation.mobile_manipulation",
    "multi_task": "vla.foundation.vla_generalist",
    "rl_finetuning": "vla.policy.robot_rl.vla_post_training_rl",
    "tactile": "vla.manipulation.tactile_sensing",
    "manipulation": "vla.manipulation",
    "imitation_learning": "vla.policy.imitation_learning",
    "robot_rl": "vla.policy.robot_rl",
    "dexterous_manipulation": "vla.manipulation.dexterous_manipulation",
    "tactile_sensing": "vla.manipulation.tactile_sensing",
    "efficient_inference": "vla.efficiency.vla_acceleration",
    "sim_to_real": "vla.sim_data.sim_to_real",
    "navigation": "vla.navigation.vision_language_navigation",
    "data_generation": "vla.sim_data.synthetic_data_generation",
}

LEAVES = [slug for slug, n in ONTOLOGY.items() if n["match_precedence"] > 0]
CATCH_ALL = {slug for slug, n in ONTOLOGY.items() if 0 < n["match_precedence"] <= 10}
KEYWORDS = {slug: n["keywords"] for slug, n in ONTOLOGY.items() if n["match_precedence"] > 0 and n["keywords"]}
DISPLAY_NAMES = {slug: n["display_name"] for slug, n in ONTOLOGY.items() if n["display_name"]}


def rank_method_families(titles):
    """Per-title family routing.

    Returns sorted [(slug, hit_count), ...] DESC. Per title: pick at most one
    family — specific (non-CATCH_ALL) families always beat catch-alls; within
    each tier the family with the most keyword hits wins.

    Mirrors the TS rankMethodFamiliesV2 exactly so server-side trends align
    with site-side display.
    """
    hits = {}
    for t in titles:
        if not t:
            continue
        title = f" {t.lower()} "
        specific_best = None
        catch_best = None
        for slug, kws in KEYWORDS.items():
            n = sum(1 for kw in kws if kw in title)
            if n == 0:
                continue
            if slug in CATCH_ALL:
                if not catch_best or n > catch_best[1]:
                    catch_best = (slug, n)
            else:
                if not specific_best or n > specific_best[1]:
                    specific_best = (slug, n)
        picked = specific_best or catch_best
        if picked:
            hits[picked[0]] = hits.get(picked[0], 0) + 1
    return sorted(hits.items(), key=lambda x: -x[1])


def resolve_v1_slug(slug):
    """Resolve a V1 slug to its V2 equivalent.

    Returns None if the V1 family has been retired (e.g. 'open_source').
    Pass-through if the input is already a V2 slug. Used for one-shot
    migration of existing JSON files.
    """
    if slug in ALIAS_V1_TO_V2:
        return ALIAS_V1_TO_V2[slug]
    if slug in ONTOLOGY:
        return slug  # already V2
    return None      # unknown — caller decides what to do


if __name__ == "__main__":
    import sys
    print(f"ONTOLOGY: {len(ONTOLOGY)} nodes")
    print(f"LEAVES: {len(LEAVES)}")
    print(f"CATCH_ALL: {len(CATCH_ALL)} ({sorted(CATCH_ALL)})")
    print(f"ALIAS_V1_TO_V2: {len(ALIAS_V1_TO_V2)} entries "
          f"({sum(1 for v in ALIAS_V1_TO_V2.values() if v is None)} retired)")
    if len(sys.argv) > 1:
        # Usage: python3 _ontology_v2.py "diffusion policy for manipulation"
        ranked = rank_method_families(sys.argv[1:])
        for slug, n in ranked[:5]:
            print(f"  {slug}: {n}")
